version: '3.8'

services:
    # Serviços
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
        environment:
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=scout_basket
            - DB_USERNAME=root
            - DB_PASSWORD=
        depends_on:
            - db
            - redis
        networks:
            - laravel_network

    # Nginx
    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel_network

    # MySQL
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    # Redis
    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
        networks:
            - laravel_network

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_pma
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: secret
        ports:
            - "8080:80"
        networks:
            - laravel_network

volumes:
    dbdata:
        driver: local
    redisdata:
        driver: local

networks:
    laravel_network:
        driver: bridge
